[Fix] Prevent container from getting stuck in restart loop
opentargets/platform-api pull request #100
Opened 2022-01-28 12:54 UTC by romanhaa

Without the added flag (`-Dpidfile.path=/dev/null`), the Docker container would get stuck in a reboot loop (with error `This application is already running (Or delete /srv/app/ot-platform-api-latest/RUNNING_PID file).` after restarting the Docker service, e.g. when the system is rebooted.

Fix was taken from: https://stackoverflow.com/a/29244028

2022-07-04 07:03 UTC, romanhaa commented
@JarrodBaker Hi! Could you please review this? We still experience this issue with the currently used image (`dev22.06.3`).

2022-07-06 13:23 UTC, JarrodBaker requested changes
Thanks for the PR @romanhaa. 

We haven't encountered this at Open Targets as we deploy the Docker container into a clean VM. 

Are you providing a custom configuration file when you launch the container? According to the [documentation](https://www.playframework.com/documentation/2.8.x/ProductionConfiguration) you can address this issue within your configuration by including the field `pidfile.path = "/dev/null"`.

2022-07-06 13:37 UTC, romanhaa commented
Thanks for the feedback @JarrodBaker. We typically don't use a custom configuration, but I suppose that would be a better solution than modifying the launch command. I will test it.

2023-08-15 08:18 UTC, fedde-s commented
I haven't seen the intention to iterate on this in a year now, and Roman is no longer working at The Hyve. I think it's simplest to close this pull request, and _if_ we ever want to get back to it, make another one with the new proposal. I don't have a close button though, can someone at EBI close it?

2025-01-31 09:44 UTC, javfg commented
A little late :laughing:, but closing! Thanks @fedde-s.

2025-01-31 09:44 UTC, closed without merging