Made number of query terms validated below a configurable threshold
opentargets/platform-api pull request #155
Opened 2023-11-23 15:10 UTC by jdhayhurst

- part of opentargets/issues#3114
- adding validator for number for query terms
- max number of query terms is configurable via environment variable, defaults to _2000_

2023-11-23 15:18 UTC, mbdebian requested changes
Thanks for the PR @jdhayhurst !
Would you mind having a look at the comment on the review request?

2023-11-23 15:18 UTC, mbdebian commented on app/models/entities/Configuration.scala
> +      maxNumberQueryTerms: Int,
We need to contextualise what this number refers to, in this case it is the number of query terms for the validation API, i.e. an example of naming would be _qValidationLimitNTerms_

2023-11-23 16:01 UTC, jdhayhurst commented on app/models/entities/Configuration.scala
> +      maxNumberQueryTerms: Int,
renamed with your suggestion

2023-11-27 14:01 UTC, mbdebian approved these changes
Thanks @jdhayhurst ! Nice job!

2023-11-27 15:16 UTC, merged